universe = vanilla

executable              = start_cpujob.sh
arguments               = "20" 
getenv = True

Request_Memory = 50960
Request_cpus = 20

log                     = ../condor_logs/cpujob_one_bin_1_10_GeV_xgam.log
output                  = ../condor_logs/outfile_one_bin_1_10_GeV_xgam.out
error                   = ../condor_logs/errors_one_bin_1_10_GeV_xgam.err

# cpu job
#+testJob = True

queue
