name = "MapGenData"
uuid = "c14a7344-00ee-4a9d-801a-689cead0fafa"
authors = ["Aurelio Amerio <aure.amerio@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
